[WINDOW]
resolution = [1280,720]
title = "Window"
GLversion = [4,6]
resizable = false

[APP]
shaderPath = "../programs"

[RT]
samples     = 2
reflections = 6
accumframes = true
skyboxpath  = "../skyboxes/planet6.png"
scenepath   = "../scenes/scene.pyrt"

[RTFX]
exposure = 1