[WINDOW]
resolution = [1280,720]
title = "Window"
GLversion = [4,6]
resizable = false

[RT]
samples     = 2
reflections = 6
accumframes = false
skyboxpath  = "../skyboxes/skybox.jpg"
scenepath   = "../scenes/scene.pyrt"